<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8C6MBSa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8C6MBSa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8C6MBSa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8C6MBSa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8C6MBSa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8C6MBSa',
    'container.build_id' => '1303cc0f',
    'container.build_time' => 1583057098,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8C6MBSa');
