<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container78PqtpH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container78PqtpH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container78PqtpH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container78PqtpH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container78PqtpH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '78PqtpH',
    'container.build_id' => '0f9759cd',
    'container.build_time' => 1583129997,
], __DIR__.\DIRECTORY_SEPARATOR.'Container78PqtpH');
